### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Daniel-Mietchen** [schmelling/clock_evo#5]
I'm not convinced CC BY-SA is the best option for making this repo useful to others. Since it is mainly documentation rather than code, what about putting it under [CC0](http://creativecommons.org/publicdomain/zero/1.0/)?

**Comment by schmelling** [comment]
I don't know much about licensing, but CC0 seems ok. Does this affect publishing of scientific results? The project involves also new research results and is only documentation right now.

**Comment by Daniel-Mietchen** [comment]
Most open-access articles are published under some version of CC BY (latest is [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)), though some are CC0. CC BY allows for inclusion of CC0 stuff, but not the other way round.

**Comment by schmelling** [comment]
I'm falling back into old patterns. I promised I use this project to try everything as open as possible. So let's do CC0
