### ISSUE TITLE
Add a data management plan

### ISSUE THREAD

**Issue by Daniel-Mietchen** [schmelling/clock_evo#6]
- [Ten Simple Rules for Creating a Good Data Management Plan](http://dx.doi.org/10.1371/journal.pcbi.1004525)
- [sample DMPs](http://riojournal.com/browse_journal_articles.php?form_name=filter_articles&selfurl=&backurl=&sortby=0&journal_id=17&search_hidden=&search_in_=0&search_in_hidden=&alerts_subject_cats=&alerts_sdg_cats=&from_date=&to_date=&section_type%5B%5D=231&section_type%5B%5D=258&funding_agency=)
- [Making DMPs actionable and public](http://www.slideshare.net/StephanieSimms/making-dmps-actionable-and-public)

**Comment by schmelling** [comment]
Looks great, will add that ASAP

**Comment by schmelling** [comment]
added a first draft in DMP.md
